name: "robin-api"

services:
  robin-api:
    container_name: robin-api
    hostname: robin-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    depends_on:
      - robin-db
    volumes:
      - ./configs:/root/configs
    restart: unless-stopped
    networks:
      - rha_local

  robin-db:
    container_name: robin-db
    image: mysql:8.4.0
    cap_add:
      - SYS_NICE
    restart: always
    env_file: .env.development
    volumes:
    - mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - rha_local

  robin-db-ui:
    container_name: robin-db-ui
    image: adminer:4.8.1
    ports:
      - "8089:8080"
    depends_on:
      - robin-db
    networks:
      - rha_local
  
  maildev:
    image: maildev/maildev
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "8086:1080"
      - "8025:1025"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
    networks:
      - rha_local

networks:
  rha_local:
    name: "rha_local_net"

volumes:
    mysql_data:
        name: "rha_mysql_data"
