listen:
  port: 3000

mysql:
  host: robin-db
  port: 3306
  username: root
  password: password
  database: rha
  debug: true
  max_open_connections: 10
  max_idle_connections: 10
  connection_max_lifetime: 0

# for testing
auth:
  jwt_secret: "eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTcyMTAxNzA5NCwiaWF0IjoxNzIxMDE3MDk0fQ._mUmD-4p7MyLJgZXLxniTCorJ_i7r3I04KhSC6JZCZo"
  password_reset_link: "http://app.rha.com"