listen:
  port: 3000

mysql:
  host: robin-db
  port: 3306
  username: root
  password: password
  database: rha
  debug: true
  max_open_connections: 10
  max_idle_connections: 10
  connection_max_lifetime: 0

aws:
  region: us-east-1
